### ISSUE TITLE
Support plugins available at link time

### ISSUE THREAD

**Issue by frutiger** [frutiger/bdemeta#14]
A plugin available at link time is a static library that is provided as a link-time dependency of some other code.  This other code may then freely use functions from the library as long the name of the exported symbols are known (e.g. through header files).

The code may also then be deployed without any further requirements.  This stands in contrast to #13, which requires the using code and the shared library to be deployed together.

This would implement option (3) from #7.

**Comment by cppguru** [comment]
Same as for the dynamic one.  The code linking the plugin in is not the
user.  As it has no specific dependencies whatsoever to the plugin at all.
It's a third piece of code that uses the plugin, and that code should be
able to require the headers without creating a link time dependency.  Why?
Because the user must not be aware if the module is dynamic or static.

**Comment by frutiger** [comment]
All generated libraries have unspecified _CMake_ library type; so static vs. dynamic libraries can be specified at _CMake_ generation time using the `BUILD_SHARED_LIBS` flag.  Either type of library can be linked to at link time.
